// frontend-project-react/src/pages/Login/index.tsx
import request from "../../request";
import qs from "qs";
import React, { useState } from "react";
import { Redirect } from "react-router-dom";
import { Form, Input, Button, message } from "antd";
import { LockOutlined } from "@ant-design/icons";
import "./style.css";

interface FormFields {
  password: string;
}

const LoginForm = (props: any) => {
  const [isLogin, setIsLogin] = useState(false);

  const onFinish = (values: any) => {
    request
      .post("api/login", qs.stringify(values), {
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
        },
      })
      .then((res) => {
        const data: responseResult.login = res.data;
        console.log(res);
        if (data) {
          setIsLogin(true);
        } else {
          message.error("login failed");
        }
      });
  };

  return isLogin ? (
    <Redirect to="/" />
  ) : (
    <div className="login-page">
      <Form
        name="normal_login"
        className="login-form"
        initialValues={{
          remember: true,
        }}
        onFinish={onFinish}
      >
        <Form.Item
          name="password"
          rules={[
            {
              required: true,
              message: "Please input your Password!",
            },
          ]}
        >
          <Input
            prefix={<LockOutlined className="site-form-item-icon" />}
            type="password"
            placeholder="Password"
          />
        </Form.Item>

        <Form.Item>
          <Button
            type="primary"
            htmlType="submit"
            className="login-form-button"
          >
            Log in
          </Button>
        </Form.Item>
      </Form>
    </div>
  );
};

export default LoginForm;

// frontend-project-vue/src/views/Login.vue
<template>
  <div class="login-page">
    <el-form :model="form" status-icon :rules="rules" ref="form">
      <el-form-item label="Password" prop="password">
        <el-input v-model="form.password"></el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="submitForm">Login</el-button>
      </el-form-item>
    </el-form>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";
import request from "../request";
import qs from "qs";

@Component
export default class Login extends Vue {
  private form = {
    password: "",
  };

  private rules = {
    password: [
      { required: true, message: "Please enter password", trigger: "blur" },
    ],
  };

  private submitForm() {
    const valid = (this.$refs.form as Vue & {
      validate: () => boolean;
    }).validate();

    if (valid) {
      request
        .post("api/login", qs.stringify({ password: this.form.password }), {
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
          },
        })
        .then((res) => {
          const data: responseResult.login = res.data;
          if (data) {
            this.$router.push("/");
          } else {
            this.$message.error("login failed");
          }
        });
    } else {
      this.$message.error("error submit!!");
      return false;
    }
  }
}
</script>

<style>
.login-page {
  width: 300px;
  padding: 20px 20px 0 20px;
  margin: 100px auto;
  border: 1px solid #ccc;
}
</style>
